# Generated by Django 5.0 on 2025-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_hours',
            field=models.IntegerField(default=0),
        ),
    ]
