# Generated by Django 5.2 on 2025-04-12 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentinstructorrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "INSTRUCTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
